name: Build and Test
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Pre install
        run: |
          /usr/bin/bash -c "apt-get update && apt-get install -y libunwind-dev libceres-dev"
      - name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          skip-tests: true
      - name: Remove flake8-quotes flake8-import-order for linter
        run: /usr/bin/bash -c "apt-get remove -y python3-flake8-quotes python3-flake8-import-order"
      - name: Test ssct_interfaces
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh ssct_interfaces
      - name: Test ssct_common
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh ssct_common
      - name: Test ssct_camera_intrinsic_calib
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh ssct_camera_intrinsic_calib
      - name: Test ssct_lidar_cam_manual_calib
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh ssct_lidar_cam_manual_calib